# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ubablog2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubtime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 15, 6, 40, 59, 814839, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
