# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubablog2', '0002_article_pubtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=32)),
                ('select1', models.CharField(max_length=32)),
                ('select2', models.CharField(max_length=32)),
                ('select3', models.CharField(max_length=32)),
                ('select4', models.CharField(max_length=32)),
                ('select5', models.CharField(max_length=32)),
                ('select6', models.CharField(max_length=32)),
                ('select7', models.CharField(max_length=32)),
                ('select8', models.CharField(max_length=32)),
                ('select9', models.CharField(max_length=32)),
                ('select10', models.CharField(max_length=32)),
            ],
        ),
    ]
