# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubablog2', '0003_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(max_length=25)),
                ('tenant_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=25)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('is_default', models.IntegerField()),
                ('is_abutment', models.IntegerField()),
                ('version_id', models.CharField(max_length=255)),
            ],
        ),
    ]
