# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubablog2', '0004_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True)),
            ],
        ),
    ]
