# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-24 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubablog2', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
